#!/bin/bash

PATH=/Users/amit.patel/Documents/CVN/EECS_E6893/Project/:/Users/amit.patel/anaconda3/envs/py3/bin:/Users/amit.patel/anaconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/opt/llvm/bin:/Users/amit.patel/.opam/default/bin:/Users/amit.patel/Downloads/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:/Users/amit.patel/Library/Android/sdk/platform-tools:/Users/amit.patel/Library/Python/3.5/bin
GOOGLE_APPLICATION_CREDENTIALS=/Users/amit.patel/Documents/CVN/EECS_E6893/Project/auth/ColumbiaE6893-e4539ff8de19.json

*/5 * * * *  cd /Users/amit.patel/Documents/CVN/EECS_E6893/Project && ./hotspotsGeneration.py >> ./out/hotspotsGenerator.out 2>&1